# -*- coding: utf-8 -*-
"""ML1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e4QJ6SlpNARM5d0ymUWOjIcn_PIAXklT
"""

import numpy as np
import pandas as pd

print("Experiment-1")

arr = np.array([1, 2, 3, 4, 5])

print("Array:", arr)
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)

print("\n")

print("Experiment-2")

zeros_matrix = np.zeros((3, 4))
ones_matrix = np.ones((2, 5))

print("Zeros Matrix:\n", zeros_matrix)
print("Shape:", zeros_matrix.shape)

print("\nOnes Matrix:\n", ones_matrix)
print("Shape:", ones_matrix.shape)

print("\n")

print("Experiment-3")

arr = np.arange(1, 13)

reshaped_arr = arr.reshape(3, 4)

print("Original Array:", arr)
print("Shape:", arr.shape)

print("\nReshaped Array:\n", reshaped_arr)
print("Shape:", reshaped_arr.shape)

print("\n")

print("Experiment-4")

random_arr = np.random.randint(1, 100, 10)

print("Array:", random_arr)
print("Minimum:", np.min(random_arr))
print("Maximum:", np.max(random_arr))
print("Mean:", np.mean(random_arr))
print("Sum:", np.sum(random_arr))

print("\n")

print("Experiment-5")

data = {
    "Name": ["Aman", "Riya", "Rahul", "Sneha"],
    "Marks": [85, 90, 78, 92]
}

df = pd.DataFrame(data)

print("DataFrame:\n", df)
print("\nData Types:\n", df.dtypes)

print("\n")

import pandas as pd
print("Experiment-6")

# Upload CSV in Colab first OR use sample dataset
df_csv = pd.read_csv("/content/Iris.csv")  # change file name if needed

print("First 5 rows:\n", df_csv.head())
print("\nLast 5 rows:\n", df_csv.tail())

print("\n")

print("Experiment-7")

print(df_csv.info())

print("\nRows and Columns:", df_csv.shape)

print("\nMissing Values:\n", df_csv.isnull().sum())

print("\n")

print("Experiment-8")

print(df_csv.describe())

# Interpretation (for viva)
print("\nInterpretation:")
print("Mean = Average value")
print("Std = Spread of data")
print("Min = Smallest value")
print("Max = Largest value")